### ISSUE TITLE
Export Schedule to .ics Format

### ISSUE THREAD

**Issue by fahdikrie** [ristekoss/susunjadwal-frontend#14]
**This issue is a:** 

- [ ] bug report
- [x] feature request
- [ ] styling change request

**Current behavior:**

We currently don't have any form of schedule-saving approach except by taking a screenshot of the timetable.

**Requested behavior:**

As requested by many on our [previous feedback form](https://airtable.com/shrkmi8pHNW5zhZFG), it'd be nice if SusunJadwal had a GCal or Apple Calendar integration. The easiest/fastest possible way for it to get done is by exporting our schedule to a universal format, such as .ics.

According to what the design team from Ristek had envisioned, the design would look like this:

<img width="560" alt="Screen Shot 2021-10-06 at 02 04 47" src="https://user-images.githubusercontent.com/47189456/136087933-0b08f25e-0581-4f88-b4fc-426ff216b346.png">

There would be a three-dot/option button that would expand to something like below:

<img width="98" alt="Screen Shot 2021-10-06 at 02 04 37" src="https://user-images.githubusercontent.com/47189456/136087926-3944fea3-3e3a-49ab-b822-4a7e912d2c3d.png">

The `Download Jadwal` button would then trigger a download pop-up, letting user to save and name the schedule in the .ics format. 

**Related Issue:**

Also see this issue on SusunJadwal's backend repository:
ristekoss/susunjadwal-backend#8

**Why this behavior is better:**

Saves a lot of hassle of having to manually input your SIAK schedule to GCal/Apple Cal.

**Comment by priambudiLB** [comment]
WIP
